apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-server
  namespace: default
  labels:
    app: cpp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpp-server
  template:
    metadata:
      labels:
        app: cpp-server
    spec:
      containers:
        - name: cpp-server
          image: cpp-server:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
