apiVersion: v1
kind: Service
metadata:
  name: cpp-server
  namespace: default
  labels:
    app: cpp-server
spec:
  type: NodePort
  selector:
    app: cpp-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
