apiVersion: v1
kind: Service
metadata:
  name: cpp-hello
  namespace: default
  labels:
    app: cpp-hello
spec:
  type: NodePort
  selector:
    app: cpp-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
